### PR TITLE
Add support for osx

### PR DESCRIPTION
**Pull request by bennibbelink**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Similar to https://github.com/conda-forge/cyclus-feedstock/pull/88, after this is merged a PR should be made to https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt to request arm support

### CODE REVIEW

**Comment by bennibbelink** [comment]
@conda-forge-admin, please rerender

**Comment by bennibbelink** [comment]
I'm not sure why the usual azure pipelines aren't being run, should probably hold off on merge until we see proper CI pass

**Comment by gonuke** [comment]
don't we need the `conda_build_config.yaml` file that sets the target as `cycamore_dev` like for Cyclus?

**Comment by bennibbelink** [comment]
It already lives in the `dev` branch https://github.com/conda-forge/cycamore-feedstock/blob/dev/recipe/conda_build_config.yaml

**Comment by bennibbelink** [comment]
Maybe this will work? @conda-forge-admin, please restart ci

Did the trick 👍

**Comment by gonuke** [comment]
> It already lives in the `dev` branch https://github.com/conda-forge/cycamore-feedstock/blob/dev/recipe/conda_build_config.yaml

Oh - I forgot that we merged a `dev` branch here already, and thought we'd only done it on cyclus.  👍

**Comment by bennibbelink** [comment]
@conda-forge-admin, please restart ci

**Comment by bennibbelink** [comment]
Closing this in favor of #28, I made a fresh branch with these changes and that seemed to fix the `git fetch` errors seen in this PR.

**Pull request closed without merging**
