### PR TITLE
bump cycamore version

### PR DESCRIPTION
**Pull request by bam241**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bam241** [comment]
@conda-forge-admin please rerender

**Comment by bam241** [comment]
@conda-forge-admin please rerender

**Comment by bam241** [comment]
@gonuke @katyhuff @FlanFlanagan this one is ready as well :)

**Comment by katyhuff** [comment]
@bam241 : Why the move from circleci to azure? Am I reading this PR properly?

**Comment by bam241** [comment]
this is Conda automatic stuff, I only changed sycamore version and the reference to cyclus version

**Comment by bam241** [comment]
I only change the meta.yml file

**Comment by katyhuff** [comment]
What a complex machine this conda-forge is!

**Pull request merged**
